# Generated by Django 2.1.4 on 2019-02-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='preciobase',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
