# Generated by Django 2.1.4 on 2019-01-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='precio',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
